### ISSUE TITLE
Document (e.g. in README) how to install and re/build the theme

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder-docs-sphinx-theme#28]
I can't find anywhere in this repo or its upstreams how to actually build the theme if I changed something (e.g. in the SCSS). In order to actually update the theme package I had to poke around in the code and on Google to figure things out, and that was after asking before to get the command to build the theme in dev mode. Therefore, it should be documented in the README. I believe the commands should be something like

```bash
pip install -e .
npm install
```
Then ``npm run build:dev`` to build the test site or ``npm run build:production`` to build the theme package for use on the docs repo, but that was with some trial and error so not 100% sure so @dalthviz please check. Thanks!

**Comment by CAM-Gerlach** [comment]
I can just go ahead with this at some point soon (™), since I'm pretty comfortable with this by now.

**Comment by ccordoba12** [comment]
Please do.
