### ISSUE TITLE
Initial improvements to theme layout and styling

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder-docs-sphinx-theme#7]
Hey @juanis2112 , @dalthviz and @ccordoba12 here are the improvements as discussed during the meeting:

* [x] Shift heading font sizes down one level
* [x] Make main font size 15 px
* [x] Change left sidebar heading and subhead sizes to 0.8rem
* [x] Change top-level left sidebar headings to uppercase style
* [x] 0.3em margin-bottom on all heading h2 and below
* [x] 1.5rem margin-bottom on images
* [x] Increase width of right sidebar by ~50-100px
* [x] Increase total content max width to ~1280 px

For now, it appears these are basic, general and interlinked enough that they should all be made in the theme.

Feel free to edit this OP if I've missed something. Thanks!

~~Edit:~~

~~* [ ] Add footer~~

**Comment by dalthviz** [comment]
Fixed with #8
